name: infra-apply

on:
  push:
    branches: ["main"]

jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_VAR_region: ${{ vars.TF_VAR_region }}
      TF_VAR_owner: ${{ vars.TF_VAR_owner }}
      TF_VAR_bucket_suffix: ${{ vars.TF_VAR_bucket_suffix }}
      TF_VAR_env: ${{ vars.TF_VAR_env }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform init
        run: terraform -chdir=infra/terraform init
      - name: Terraform apply
        run: terraform -chdir=infra/terraform apply -auto-approve
