name: infra-apply

on:
  push:
    branches: ["main"]
    paths:
      - "infra/terraform/**"

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: production
    env:
      TF_VAR_region: ${{ vars.TF_VAR_region }}
      TF_VAR_owner: ${{ vars.TF_VAR_owner }}
      TF_VAR_bucket_suffix: ${{ vars.TF_VAR_bucket_suffix }}
      TF_VAR_env: ${{ vars.TF_VAR_env }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::026544697610:role/mlops-lite-github-oidc-dev
          aws-region: eu-central-1
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform init
        run: terraform -chdir=infra/terraform init -upgrade
      - name: Terraform apply
        run: terraform -chdir=infra/terraform apply -auto-approve
